version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/webapp

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: ./codedeploy/stop.sh
      timeout: 300
      rusas: ubuntu
    
  BeforeInstall:
    - location: ./codedeploy/before_install.sh
      timeout: 300
      runas: ubuntu
      
  AfterInstall:
    - location: ./codedeploy/post_install.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: ./codedeploy/start.sh
      timeout: 300
      runas: ubuntu