name: Build & Deploy WebApp

env:
  # ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
  CODEDEPLOY_APPLICATION_NAME: ${{ secrets.codedeploy_application_name }}
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: ${{ secrets.codedeploy_application_deployment_group_name }}
  AWS_REGION: ${{ secrets.aws_region }}
  AWS_CODEDEPLOY_BUCKET: ${{ secrets.codedeploy_bucket }}

on:
  push:
    branches: [ master ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ secrets.node_version }}
    - run: npm i

    - name: Build Artifact
      run: |
        mkdir artefacts
        tar cfz artefacts/webapp.tgz --exclude=./artefacts .
        cd artefacts
        pwd
        ls -ltr

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ secrets.aws_region }}

    - name: Push artifact to S3
      run: |
        aws s3 sync ./artefacts s3://${{ secrets.codedeploy_bucket }}

    - name: CodeDeploy API call
      run: |
        output=$(aws deploy create-deployment \
          --application-name ${{ secrets.codedeploy_application_name }} \
          --deployment-group-name ${{ secrets.codedeploy_application_deployment_group_name }} \
          --description "CSYE6225 - CodeDeploy" \
          --s3-location bucket=${{ secrets.codedeploy_bucket }},key=webapp.tgz,bundleType=tgz \
          --region ${{ secrets.aws_region }} \
          --output json)
          echo $output
          did=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $did
