name: NodeJS Test

on:
  pull_request:
    branches: [ master ]
jobs:
  webapp_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test in Node.js with JestJS
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ env `node_version` }}

      - run: npm test
